name: ar_project
description: "Captures an image from Brilliant Labs Frame and sends it to a user-specified API for processing"
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  flutter_quick_video_encoder: ^1.7.2
  flutter_blue_plus: ^1.34.5
  frame_ble: ^3.0.0
  path_provider: ^2.1.3
  flutter_foreground_task: ^6.5.0
  frame_msg: ^2.0.0
  http: ^1.2.2
  http_parser: ^4.0.2
  image: ^4.3.0
  logging: ^1.3.0
  share_plus: ^10.1.0
  shared_preferences: ^2.3.2
  simple_frame_app: ^7.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - packages/frame_msg/lua/battery.min.lua
    - packages/frame_msg/lua/camera.min.lua
    - packages/frame_msg/lua/code.min.lua
    - packages/frame_msg/lua/data.min.lua
    - packages/frame_msg/lua/plain_text.min.lua
    - packages/frame_msg/lua/imu.min.lua
    - assets/frame_app.lua