name: ar_project
description: "A new Flutter project."
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  permission_handler: ^11.3.1
  frame_ble: ^3.0.0
  logging: ^1.2.0
  image: ^4.3.0
  sembast: ^3.8.5
  frame_msg: ^2.0.0
  path_provider: ^2.1.5
  cupertino_icons: ^1.0.8
  path: ^1.8.3
  file_picker: ^10.1.7  # removed per previous workaround
  frame_sdk: ^0.0.7

assets:
  - assets/lua/

dependency_overrides:
  meta: ^1.11.0
  collection: ^1.17.1
  archive: ^4.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true